#ifndef INCLUDE_FLAMEGPU_RUNTIME_CURVE_CURVEINSTANCE_H_
#define INCLUDE_FLAMEGPU_RUNTIME_CURVE_CURVEINSTANCE_H_

#include "flamegpu/runtime/cuRVE/curve.h"


#endif  // INCLUDE_FLAMEGPU_RUNTIME_CURVE_CURVEINSTANCE_H_

