package:
  name: "pyflamegpu"
  version: "2.0.0rc1"

source:
  # Use the current committed state of the repo, to avoid pinning versions or copying the build directory if using path.
  git_url: ../../
  # git_url: https://github.com/FLAMEGPU/FLAMEGPU2.git
  # git_rev: v2.0.0-rc
  # git_depth: 1 # Shallow
  
# requires: conda config --add channels conda-forge
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cuda-cudart-dev # [linux]
    - libcurand-dev # [linux]
    - cuda-nvrtc-dev # [linux]
    - swig ==4.0.2 # Have to manually direct swig to find this
    - cmake
    - python
    - python-devtools
    - pip
    - setuptools >=40.8.0
    - wheel
    - build
    - astpretty
  run:
    - python
    - cuda-toolkit

build:
  # Allow certain env vars to be passed through to build.sh. this seems to set warnings...
  # Probably need to add other env vars CMake might expect to this?
  script_env:
    - FLAMEGPU_CONDA_BUILD_THREADS
    - FLAMEGPU_CONDA_CUDA_ARCHITECTURES
#  track_features:
#    - feature2
#  run_exports:
#    strong:
#      - _pyflamegpu
#      - libnvrtc
#      - libcuda
#      - libcudart
#      - libdl
#      - libstdc++
#      - libgcc
#      - librt
#      - libpthread
      
test:
  imports:
    - pyflamegpu

about:
  home: https://flamegpu.com/
  license: MIT
  license_family: MIT
  summary: GPU accelerated agent based modelling framework for Python