/**${SHORT_HASH}
 * This file is automatically generated at CMake configure time, do not modify
 */
#ifndef INCLUDE_FLAMEGPU_VERSION_H_
#define INCLUDE_FLAMEGPU_VERSION_H_

#include <string>

namespace flamegpu_internal {
inline std::string getCommitHash() {
    return "${SHORT_HASH}";
}
}  // namespace flamegpu_internal

#endif  // INCLUDE_FLAMEGPU_VERSION_H_