# Just build documentation using Doxygen - no CUDA required
name: Docs

on:
  push:
  pull_request:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    env:
      Werror: "ON"
    steps:
    - uses: actions/checkout@v2

    - name: Install doxygen
      run: sudo apt -y install doxygen graphviz

    - name: Configure cmake
      run: cmake . -B build -DBUILD_API_DOCUMENTATION=ON -DWARNINGS_AS_ERRORS=${{ env.Werror }}

    - name: Docs
      run: cmake --build . --target docs --verbose -j `nproc`
      working-directory: build
